-- USER_INFO 테이블과 ONLINE_SALE 테이블에서 년, 월, 성별 별로 상품을 구매한 회원수를 집계하는 SQL문을 작성해주세요. 
-- 결과는 년, 월, 성별을 기준으로 오름차순 정렬해주세요. 이때, 성별 정보가 없는 경우 결과에서 제외해주세요.
SELECT TO_CHAR(S.SALES_DATE, 'YYYY') AS YEAR, TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM')) AS MONTH, I.GENDER, COUNT(DISTINCT S.USER_ID) AS USERS
FROM USER_INFO I JOIN ONLINE_SALE S
ON I.USER_ID = S.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY TO_CHAR(S.SALES_DATE, 'YYYY'), TO_CHAR(S.SALES_DATE, 'MM'), GENDER
ORDER BY YEAR, MONTH, GENDER