--7월 아이스크림 총 주문량과 상반기의 아이스크림 총 주문량을 더한 값이 큰 순서대로 상위 3개의 맛을 조회하는 SQL 문을 작성해주세요.

SELECT FLAVOR
FROM 
(
    SELECT A.FLAVOR, (SUM(A.TOTAL_ORDER) + SUM(B.TOTAL_ORDER)) AS TOTAL
    FROM FIRST_HALF A, JULY B
    WHERE A.FLAVOR = B.FLAVOR
    GROUP BY A.FLAVOR
    ORDER BY TOTAL DESC
) AS TOTAL_TB LIMIT 3