-- 2022년 1월의 도서 판매 데이터를 기준으로 저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가) 을 구하여, 
-- 저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카테고리(CATEGORY), 매출액(SALES) 리스트를 출력하는 SQL문을 작성해주세요.
-- 결과는 저자 ID를 오름차순으로, 저자 ID가 같다면 카테고리를 내림차순 정렬해주세요

WITH SALES_TB AS 
(SELECT B.AUTHOR_ID, B.CATEGORY, (B.PRICE * SALES) AS TOTAL_SALES
FROM BOOK B JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID
WHERE TO_CHAR(S.SALES_DATE, 'MM') = 1)

SELECT T.AUTHOR_ID, A.AUTHOR_NAME, T.CATEGORY,SUM(TOTAL_SALES) AS TOTAL_SALES
FROM SALES_TB T JOIN AUTHOR A
ON T.AUTHOR_ID = A.AUTHOR_ID
GROUP BY T.AUTHOR_ID, T.CATEGORY, A.AUTHOR_NAME
ORDER BY T.AUTHOR_ID, T.CATEGORY DESC