-- CAR_RENTAL_COMPANY_CAR 테이블과 CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블과 
-- CAR_RENTAL_COMPANY_DISCOUNT_PLAN 테이블에서 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서 대여 기록 별로 대여 
-- 금액(컬럼명: FEE)을 구하여 대여 기록 ID와 대여 금액 리스트를 출력하는 SQL문을 작성해주세요. 
-- 결과는 대여 금액을 기준으로 내림차순 정렬하고, 대여 금액이 같은 경우 대여 기록 ID를 기준으로 내림차순 정렬해주세요. 

WITH CAR_DISCOUNT AS 
(
    SELECT REGEXP_REPLACE(DURATION_TYPE, '[^0-9]') AS TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE CAR_TYPE = '트럭'
),
CAR_FEE AS 
(
    SELECT H.HISTORY_ID, 
    CASE 
        WHEN H.END_DATE - H.START_DATE + 1 >= 90 THEN 90
        WHEN H.END_DATE - H.START_DATE + 1 >= 30 THEN 30
        WHEN H.END_DATE - H.START_DATE + 1 >= 7 THEN 7
        ELSE H.END_DATE - H.START_DATE + 1
    END AS FEE_TYPE, 
    H.END_DATE - H.START_DATE + 1 AS DURATION,
    C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE ='트럭'
)

SELECT F.HISTORY_ID, 
(NVL((100 - D.DISCOUNT_RATE)*0.01,1) * DAILY_FEE * DURATION) AS FEE
FROM CAR_FEE F LEFT JOIN CAR_DISCOUNT D
ON F.FEE_TYPE = D.TYPE
ORDER BY FEE DESC, F.HISTORY_ID DESC

