-- CAR_RENTAL_COMPANY_CAR 테이블과 
-- CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블과 
-- CAR_RENTAL_COMPANY_DISCOUNT_PLAN 테이블에서 
-- 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고 
-- 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차에 대해서 자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE) 리스트를 출력하는 SQL문을 작성해주세요. 
-- 결과는 대여 금액을 기준으로 내림차순 정렬하고, 대여 금액이 같은 경우 자동차 종류를 기준으로 오름차순 정렬, 자동차 종류까지 같은 경우 자동차 ID를 기준으로 내림차순 정렬해주세요.
SELECT CAR.CAR_ID, CAR_FEE.CAR_TYPE, (CAR.DAILY_FEE * CAR.PERIOD * CAR_FEE.DISCOUNT_RATE * 0.01) AS FEE
FROM (
        SELECT C.CAR_ID, CAR_TYPE, DAILY_FEE, (END_DATE - START_DATE) AS PERIOD
        FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE C.CAR_ID = H.CAR_ID 
        AND CAR_TYPE IN ('세단','SUV')
        AND TO_CHAR(END_DATE,'YYYY-MM-DD') <='2022-11-30'
        AND TO_CHAR(END_DATE,'YYYY-MM-DD') >='2022-11-01'
        AND (END_DATE - START_DATE) >= 30
    ) CAR, 
    (
        SELECT CAR_TYPE, DISCOUNT_RATE 
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
        WHERE CAR_TYPE IN ('세단','SUV') 
        AND DURATION_TYPE LIKE '%30%'
    ) CAR_FEE
WHERE CAR.CAR_TYPE = CAR_FEE.CAR_TYPE
AND (CAR.DAILY_FEE * CAR.PERIOD * CAR_FEE.DISCOUNT_RATE * 0.01)< 2000000 
AND (CAR.DAILY_FEE * CAR.PERIOD * CAR_FEE.DISCOUNT_RATE * 0.01) >= 500000
ORDER BY FEE, CAR_FEE.CAR_TYPE DESC, CAR.CAR_ID DESC    
-- SELECT (A.DAILY_FEE * 30 * DISCOUNT_RATE* 0.01) as fee
-- FROM CAR_RENTAL_COMPANY_CAR A, (SELECT CAR_TYPE, DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE IN ('세단','SUV') AND DURATION_TYPE LIKE '%30%') B 
-- WHERE A.CAR_TYPE = B.CAR_TYPE